### ISSUE TITLE
"Leapcast requires Python >= 2.7, < 3, but found 3.4.0" ?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [dz0ny/leapcast#108]
Why can't it run on newer versions?

**Comment by justin8** [comment]
1) install python
2) install pip
3) `pip install leapcast`

It doesn't exactly need an instruction manual. I have no idea in windows, I haven't used it in a long time. But every linux or mac system you just need to run `$packagemanager install python python-pip` (or python2 and python2-pip for fedora/arch/etc) and you're done.
