### ISSUE TITLE
Implement Chrome Cast v2 API

### ISSUE THREAD

**Issue by werty1st** [dz0ny/leapcast#114]
Can someone provide any background information about the topic?

Implement Chrome Cast channel on port 8009
has this something to do with this?
https://code.google.com/p/chromium/issues/detail?id=238819

can't an other browser engine be used? or can't the requestes be proxied and sent to different ports of the browser?

and isn't there an other problem with the certificate checking?
https://github.com/dz0ny/leapcast/issues/96#issuecomment-37932415

more infos:
https://github.com/jloutsenhizer/CR-Cast/wiki/Chromecast-Implementation-Documentation-WIP

**Comment by candrews** [comment]
There's a pretty good write up of the v2 protocol at https://github.com/thibauts/node-castv2 - I'm still holding out hope that someday I can use a computer as a ChromeCast :)

**Comment by werty1st** [comment]
Maybe we could run the modified chromecast.apk from http://forum.xda-developers.com/hardware-hacking/chromecast/app-cast-receiver-app-android-t2900726
inside chrome:
http://www.omgubuntu.co.uk/2014/09/install-android-apps-ubuntu-archon

i have installed the apk on my Minix Neo and it works at least with google music.
