### ISSUE TITLE
Support for Android 5.0 Lollipop screencast feature

### ISSUE THREAD

**Issue by geovanisouza92** [dz0ny/leapcast#123]
Hi, thank you for this amazing project.

I'd tested on Ubuntu with my Lollipop smartphone and all worked fine on apps like Youtube, Play Music, etc.

But, the built-in feature for screencast Android screen doesn't worked.

There is plan for support this?

**Comment by quantenschaum** [comment]
Lollipop PlayMusic is working? I doubt that it does, due to protocol change. Is your PlayMusic app up to date?

**Comment by geovanisouza92** [comment]
Play Music v5.7.1788Q.1634597 not even recognized

**Comment by The-QullzToxic** [comment]
I can also confirm that lolipop screan cast does not work

**Comment by djdesign** [comment]
Samsung Note 4 Lollipop 5.0.1 +  Play Music v5.8.1836R 178745 does not show as well. How can I go about helping with this?

**Comment by curiousercreative** [comment]
Throwing my support behind this feature. This is a brilliant project with huge potential.
