### ISSUE TITLE
how do i start it, i already installed it?

### ISSUE THREAD

**Issue by ghost** [dz0ny/leapcast#126]
how do i start it, i already installed it!

**Comment by quantenschaum** [comment]
RTFM https://github.com/dz0ny/leapcast
;)

**Comment by reedstrm** [comment]
TFM is missing a step after 'python setup install' 'leapcast'

**Comment by quantenschaum** [comment]
run 

    leapcast

and 

    leapcast -h

to get a list possible options

TFM is not missing a step, have a look into the last box of code on 
https://github.com/dz0ny/leapcast

**Comment by nflshadow** [comment]
The step is not missing, but at the first glance, we can think the box of code is for windows only so i didn't read it. Missing a title that clearly indicate that for running.
