### ISSUE TITLE
Support for audio only play

### ISSUE THREAD

**Issue by grandrew** [dz0ny/leapcast#129]
Google recently introduced audio casting http://chrome.blogspot.ru/2015/01/introducing-google-cast-for-audio.html

I sugggest adding `--audio-only` option to leapcast. I can not yet imagine how that could be implemented though.

This feature would be handy for using PC speaker system to just play audio from a chromebook that usially features very poor speakers - but still have the video playing at the chromebook

**Comment by dz0ny** [comment]
For that we need captured traffic between such device(that only supports audio) and client. Last time I checked that traffic was encrypted with one-time PKI, so not much hope here :)

**Comment by grandrew** [comment]
Here is what official docs say about it:

- https://developers.google.com/cast/docs/audio
- https://developers.google.com/cast/docs/custom_receiver.html#capabilities

from the first doc it seems that it is not possible to stream audio only if the app is video+audio, and/or the app must somehow explicitly support streaming of audio only (I guess that youtube does that?)

the second doc seems to point that the only thing that distinguishes audio-only and video+audio devices is the `CAST-DEVICE-CAPABILITIES: {"display_supported":false}` header that should be sent with the request if there is no display support, and the app should take care of the rest. As far as I understand, this means that the chrome should be somehow instructed to attach this header to the request, and according to http://peter.sh/experiments/chromium-command-line-switches/ - there is no way to do this at commandline args.

**Comment by dz0ny** [comment]
They use headless chrome (something like phantomjs) for audio only device. About the request header, that can be done with chrome extension https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj and others...

**Comment by DanielSmedegaardBuus** [comment]
Wait a minute... You can use `phantomjs` for setting up a headless receiver? I'd love to be able to stream audio to my Ubuntu server, but installing a desktop onto it is just not something I'm ready to do. Please tell me more :)

**Comment by robUx4** [comment]
The `CAST-DEVICE-CAPABILITIES` header is*sent* by the Chromecast. So it needs to connect to something to provide that information.

**Comment by chocol4te** [comment]
@DanielSmedegaardBuus I feel the exact same way. Do you know how to setup phantomjs to work on Ubuntu Server with leapcast? I have a vm that I can set to output audio through my onboard audio, while keeping my headphones on my DAC. This would mean that my family could stream youtube music over our speaker system, and I could still work with my headphones.
