### ISSUE TITLE
Rendering to Kodi

### ISSUE THREAD

**Issue by Sandarr95** [dz0ny/leapcast#143]
Hi dz0ny, if you're still here...

So I read about the state of things with the API being shutdown and with that this project,
but I still have an idea for how I would love to use it. 

If I start leapcast now, I can still use YouTube, which was most important to me anyway.
I made a task to start it up on system boot which works, but I also use [Kodi](http://kodi.tv).
When I want to start streaming YouTube it starts properly but it doesnt claim the window focus.
I tried to fix that but then I thought it would maybe be possible to make leapcast integrate with kodi.
The video would get rendered in kodi itself so sending youtube videos to kodi is as easy as chromecasting them (as opposed to having to share it through the share-menu and a third-party app).

I believe you're using Chrome to render the video somehow and I wondered if you could give me some insights if it might be portable. Either sending the link to kodi to play, or moving the rendering software to take place within the kodi window.

Hope to hear from you,

Sander.

PS. I couldn't find the tag to say this is a question, not a long time user of github yet.

**Comment by dz0ny** [comment]
I believe this still works https://github.com/aykevl/plaincast :) In theory you could use old YT protocol which used DIAL protocol to make it compatible with Kodi. Parts of this projects can be used for that but you would have to emulate browser in python, the above mentioned plancast does this.

**Comment by Sandarr95** [comment]
I think the best solution in terms of hours vs. reward is just starting:
`chrome --start-fullscreen --kiosk youtube.com/tv`
which can be done from within kodi and made a little cleaner with batch scripting (or shell).

Thanks a lot for now, hopefully Google is still gonna be smart enough to open up the API again.

Ill close it now, so if anyone ever reads this, I think the solution described above is most rewarding.
If you need more help with setting that up, feel free to contact me.
