### ISSUE TITLE
Chromcast not detected

### ISSUE THREAD

**Issue by Wikiwix** [dz0ny/leapcast#24]
Hello,

I don't get it running. Installing it worked fine, when I start it I get this:

D:\Eigene Dateien\Eigene Downloads\leapcast-master>python leapcast --chrome "C:/Program Files (x86)/
Google/Chrome/Application/chrome.exe" -d
DEBUG:Leapcast:Added ChromeCast app
DEBUG:Leapcast:Added YouTube app
DEBUG:Leapcast:Added PlayMovies app
DEBUG:Leapcast:Added GoogleMusic app
DEBUG:Leapcast:Added GoogleCastSampleApp app
DEBUG:Leapcast:Added GoogleCastPlayer app
DEBUG:Leapcast:Added TicTacToe app
DEBUG:Leapcast:Added Fling app

but nothing happens(not sure if a chrome tab should open or something...)
and I don't get any failure if I change to a wrong chrome path...
And no Chromcast detected in the chrome app, my tablet and smartphone in youtube/play music/play movies

What can I do?

Win7x64 Python2.7.5 Chrome 29 beta

**Comment by Majal** [comment]
Question: What port and protocol is `leapcast` using?

I'm on Linux and am using `ufw` firewall. When disabled, the devices detects my computer. I wanted the firewall to be enabled though, and only open (allow) the port and protocol that `leapcast` uses. So then the question above.

Thanks!

**Comment by Majal** [comment]
After a few minutes it was working...
And the answer is:
**TCP port 8008**

Thanks to:
`netstat -n -A inet | grep 192\.168`
and
`lsof -i | grep leapcast`

-----
And the `ufw` rule should be:

`sudo ufw allow 8008/tcp`
