### ISSUE TITLE
Development with LeapCast

### ISSUE THREAD

**Issue by cucko** [dz0ny/leapcast#29]
Is there a way to register my receiver app on LeapCast?
I'm outside of US, but i want to start developing apps for ChromeCast. While i'm waiting for my device to come here from US, is there a way to start developing with LeapCast?

**Comment by joimagg** [comment]
Is it possible to add apps. F.ex. Monopoly Dash ? Really wanted to try this game out, but I don't have Chromecast or a TV for that matter. But managed to get leapcast up and running with youtube and other supported apps.
